// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.0 developer.glb -T
// Files: developer.glb [981.62KB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/developer-transformed.glb [395.08KB] (60%)
// */

// import React, { useEffect, useRef } from "react";
// import { useGraph } from "@react-three/fiber";
// import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
// import { SkeletonUtils } from "three-stdlib";

// const Developer = ({ animationName = "idle", ...props }) => {
//   const group = useRef();

//   const { scene } = useGLTF("/models/animations/developer.glb");
//   const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
//   const { nodes, materials } = useGraph(clone);

//   const { animations: idleAnimation } = useFBX("/models/animations/idle.fbx");
//   const { animations: saluteAnimation } = useFBX(
//     "/models/animations/salute.fbx"
//   );
//   const { animations: clappingAnimation } = useFBX(
//     "/models/animations/clapping.fbx"
//   );
//   const { animations: victoryAnimation } = useFBX(
//     "/models/animations/victory.fbx"
//   );

//   idleAnimation[0].name = "idle";
//   saluteAnimation[0].name = "salute";
//   clappingAnimation[0].name = "clapping";
//   victoryAnimation[0].name = "victory";

//   const { actions } = useAnimations(
//     [
//       idleAnimation[0],
//       saluteAnimation[0],
//       clappingAnimation[0],
//       victoryAnimation[0],
//     ],
//     group
//   );

//   // useEffect(() => {
//   //   if (!actions || !actions[animationName]) return;
//   //   const action = actions[animationName];
//   //   action.reset().fadeIn(0.5).play();
//   //   return () => {
//   //     if (action && action.fadeOut) action.fadeOut(0.5);
//   //   };
//   // }, [animationName, actions]);
//   // useEffect(() => {
//   //   if (!actions || !actions[animationName]) return;

//   //   const action = actions[animationName];

//   //   // Store the current action in a ref to avoid closure issues
//   //   const actionRef = { current: action };

//   //   // Play animation
//   //   action.reset().fadeIn(0.5).play();

//   //   return () => {
//   //     const currentAction = actionRef.current;

//   //     // Check if action still exists and is valid
//   //     if (
//   //       currentAction &&
//   //       typeof currentAction.fadeOut === "function" &&
//   //       currentAction !== actions[animationName]
//   //     ) {
//   //       // Only cleanup if it's not the current active action

//   //       currentAction.fadeOut(0.5).stop();
//   //     }
//   //   };
//   // }, [animationName, actions]);

//   useEffect(() => {
//     console.log("Available actions:", Object.keys(actions || {}));
//     console.log("Requested animation:", animationName);

//     // if (!actions || !actions[animationName]) {
//     if (
//       !actions ||
//       Object.keys(actions).length === 0 ||
//       !actions[animationName]
//     ) {
//       console.warn(
//         `Action "${animationName}" not found in:`,
//         Object.keys(actions || {})
//       );
//       return;
//     }

//     const action = actions[animationName];
//     console.log("Playing action:", action);

//     action.reset().fadeIn(0.5).play();

//     return () => {
//       console.log("Cleaning up action:", action);
//       if (action && typeof action.fadeOut === "function") {
//         try {
//           action.fadeOut(0.5);
//           console.log("Fade out started");
//         } catch (error) {
//           console.error("Error in fadeOut:", error);
//         }
//       } else {
//         console.warn("Action or fadeOut not available for cleanup");
//       }
//     };
//   }, [animationName, actions]);

//   return (
//     <group ref={group} {...props} dispose={null}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Hair.geometry}
//         material={materials.Wolf3D_Hair}
//         skeleton={nodes.Wolf3D_Hair.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Glasses.geometry}
//         material={materials.Wolf3D_Glasses}
//         skeleton={nodes.Wolf3D_Glasses.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//         material={materials.Wolf3D_Body}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
//         material={materials.Wolf3D_Outfit_Bottom}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={materials.Wolf3D_Outfit_Footwear}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={materials.Wolf3D_Outfit_Top}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
//       <skinnedMesh
//         name="EyeLeft"
//         geometry={nodes.EyeLeft.geometry}
//         material={materials.Wolf3D_Eye}
//         skeleton={nodes.EyeLeft.skeleton}
//         morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="EyeRight"
//         geometry={nodes.EyeRight.geometry}
//         material={materials.Wolf3D_Eye}
//         skeleton={nodes.EyeRight.skeleton}
//         morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={materials.Wolf3D_Skin}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Teeth"
//         geometry={nodes.Wolf3D_Teeth.geometry}
//         material={materials.Wolf3D_Teeth}
//         skeleton={nodes.Wolf3D_Teeth.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
//       />
//     </group>
//   );
// };

// useGLTF.preload("/models/animations/developer.glb");

// export default Developer;

import React, { useEffect, useRef, useMemo } from "react";
import { useGraph } from "@react-three/fiber";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

const Developer = ({ animationName = "idle", ...props }) => {
  const group = useRef();

  // 1. Load the model and Clone it safely
  const { scene } = useGLTF("/models/animations/developer.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  // 2. Load the animations
  const { animations: idleAnim } = useFBX("/models/animations/idle.fbx");
  const { animations: saluteAnim } = useFBX("/models/animations/salute.fbx");
  const { animations: clappingAnim } = useFBX(
    "/models/animations/clapping.fbx"
  );
  const { animations: victoryAnim } = useFBX("/models/animations/victory.fbx");

  // 3. ✅ FIX: Rename animations safely inside useMemo
  // This ensures we don't mutate data during render
  // const animations = useMemo(() => {
  //   // We clone the first clip to ensure we don't mutate the original cache
  //   const idle = idleAnim[0].clone();
  //   const salute = saluteAnim[0].clone();
  //   const clapping = clappingAnim[0].clone();
  //   const victory = victoryAnim[0].clone();

  //   idle.name = "idle";
  //   salute.name = "salute";
  //   clapping.name = "clapping";
  //   victory.name = "victory";

  //   return [idle, salute, clapping, victory];
  // }, [idleAnim, saluteAnim, clappingAnim, victoryAnim]);

  //: this is replaced after home 
  const animations = useMemo(() => {
    const idle = idleAnim[0].clone();
    const salute = saluteAnim[0].clone();
    const clapping = clappingAnim[0].clone();
    const victory = victoryAnim[0].clone();

    // Helper function to remove tracks for missing bones
    const filterTracks = (clip) => {
      // Remove tracks that try to move "Armature"
      clip.tracks = clip.tracks.filter(
        (track) => !track.name.includes("Armature")
      );
      return clip;
    };

    idle.name = "idle";
    salute.name = "salute";
    clapping.name = "clapping";
    victory.name = "victory";

    return [
      filterTracks(idle),
      filterTracks(salute),
      filterTracks(clapping),
      filterTracks(victory),
    ];
  }, [idleAnim, saluteAnim, clappingAnim, victoryAnim]);

  // 4. Bind animations to the group
  const { actions } = useAnimations(animations, group);

  // 5. Handle Animation Playback
  useEffect(() => {
    // Safety check: ensure the requested animation exists
    const action = actions?.[animationName];

    if (!action) {
      console.warn(`Animation "${animationName}" not found.`);
      return;
    }

    // Reset and play
    action.reset().fadeIn(0.5).play();

    // Cleanup: fade out on unmount or change
    return () => {
      action.fadeOut(0.5);
    };
  }, [animationName, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
};

// Preload all assets to prevent waterfalls
useGLTF.preload("/models/animations/developer.glb");
useFBX.preload("/models/animations/idle.fbx");
useFBX.preload("/models/animations/salute.fbx");
useFBX.preload("/models/animations/clapping.fbx");
useFBX.preload("/models/animations/victory.fbx");

export default Developer;
